[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Acorn precision farming rover"
authors = [{name = "Sequoia Alexander", email = "taylor@twistedfields"}]
dynamic = ["version", "description"]
